spring.application.name=fieldops-service-platform-api

spring.datasource.url=${FIELDOPS_DB_URL:jdbc:postgresql://localhost:5432/fieldops-db}
spring.datasource.username=${FIELDOPS_DB_USERNAME:postgres}
spring.datasource.password=${FIELDOPS_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=${FIELDOPS_OIDC_ISSUER_URI:http://localhost:8180/realms/fieldops}
spring.security.oauth2.resourceserver.jwt.audiences[0]=${FIELDOPS_OIDC_AUDIENCE:fieldops-api}

spring.security.oauth2.resourceserver.jwt.authorities-claim-name=roles
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_

fieldops.security.allowed-origins=${FIELDOPS_ALLOWED_ORIGINS:http://localhost:3000}

